Large map utilities
inverted-ai/invertedai pull request #197
Opened 2024-03-22 23:33 UTC by KieranRatcliffeInvertedAI

Some minor updates to AreaDriver including functioning in-simulation visualization.

2024-03-26 18:39 UTC, Ruishenl requested changes
It looks like the extra tab spaces you added here is not align with the core package anymore. Can you remove the extra tab space ? I think the standard is 4 spaces. it also makes things easier to review

2024-04-03 23:26 UTC, KieranRatcliffeInvertedAI commented
I've made the change back to spaces from tabs. I've also added a change so that the quadtree splitting condition is not just if the number of agents within the leaf node is above the capacity, but it also includes a buffer zone around the leaf node. This is as opposed to checking a bubble around each agent for neighbouring agents which should save execution time and allow for easier tuning of agent density.

2024-04-03 23:32 UTC, Ruishenl commented on invertedai/utils.py
> +        return (map_center[0] - width) < center[0] < (map_center[0] + width) and
```suggestion
        return (map_center[0] - width) < center[0] < (map_center[0] + width) and  \
```

2024-04-03 23:41 UTC, Ruishenl approved these changes

2024-04-04 16:26 UTC, merged