Traffic light doc string updates
inverted-ai/invertedai pull request #205
Opened 2024-04-24 18:16 UTC by rf-ivtdai

Update `traffic_lights_states` and `light_recurrent_states` doc strings in initialize and drive request and response.

2024-04-24 18:53 UTC, adscib reviewed
Make sure to also update `docs/source/userguide.md`.

2024-04-24 23:17 UTC, rf-ivtdai commented
![Screenshot from 2024-04-24 16-14-07](https://github.com/inverted-ai/invertedai/assets/141082125/4a48f78a-2de9-4dee-b605-2db934283b9f)

Built html docs page locally, can see `userguide.md` is updated,  `model_config` and `model_fields` are excluded from pythonapi docs. Doc strings in request and response fields needs to be merged to the `documentation` branch before it can take effect in the docs

2024-04-26 23:09 UTC, adscib requested changes
Thanks. We just need some clarification regarding whether the user can continue relying on the recurrent light states once they provide specific light states at some step. I was under the impression that they can't but maybe that's changed.

2024-04-26 23:09 UTC, adscib commented on invertedai/api/drive.py
>         in traffic_lights_states, then pass in light_recurrent_states as usual.
Does this actually work? I thought that once you pass the light states, it's game over for the server controller.

2024-04-29 19:05 UTC, rf-ivtdai commented on docs/source/userguide.md
> +light states through 'light_recurrent_states'.
Updated all doc strings according to the comments. I think things are pretty clear in the request and response, but when putting everything together here, I'm not sure if this is both clear and succinct for the purpose of a general user guide.

2024-04-29 19:45 UTC, adscib approved these changes
Nice. I think it will have to do for the user guide for now. Just one nitpick left.

2024-04-29 19:45 UTC, adscib commented on invertedai/api/drive.py
> +       If neither 'traffic_lights_states' nor 'light_recurrent_states' are provided, the server will realistically initialize the traffic light states,
```suggestion
       If neither 'traffic_lights_states' nor 'light_recurrent_states' are provided, the server will arbitrarily initialize the traffic light states,
```
I don't think the server will consider the current vehicle positions when setting the light states, so I wouldn't call it realistic.

2024-04-29 21:08 UTC, merged