add validation decorators
inverted-ai/invertedai pull request #77
Opened 2022-11-04 00:24 UTC by AlirezaMorsali

I have started the code for more validation on the client side.
Wanted to check if it's in the right direction before spending more time on it.

2022-11-04 03:35 UTC, Ruishenl commented
I could be wrong but to me decorators are useful when one can be shared in multiple places or make the code structure less messy. If each decorator is only working for a specific function then why not just use a function instead

2022-11-04 15:48 UTC, AlirezaMorsali commented
> I could be wrong but to me decorators are useful when one can be shared in multiple places or make the code structure less messy. If each decorator is only working for a specific function then why not just use a function instead

I know it's syntax abuse and I had it as a function first. I thought it may be cleaner as it adds one line to the main function. I can rewrite it as a function.

2022-11-04 18:56 UTC, adscib requested changes
Good idea to ask for feedback early. Generally, what we're after here is to catch inputs that would produce some error and provide a helpful message instead, without calling the API.

2022-11-04 18:56 UTC, adscib commented on invertedai/api/validations.py
> +            raise InvalidInputType("iai.drive: invalid input type.")
Those errors should be as specific as possible, allowing the user to easily debug things.

2022-11-04 18:56 UTC, adscib commented on invertedai/api/validations.py
> +    def wrapped_drive(
This is unnecessarily complicated. There is no reuse, so you can just insert the validation code block into the relevant function (drive/initialize/etc.).

2022-11-04 18:56 UTC, adscib commented on invertedai/api/validations.py
> +            assert isinstance(random_seed, (int, type(None)))
It's generally desirable to allow for duck typing in Python, accepting objects that have different types but the same interface. As a rule of thumb, if the rest of the function was going to execute correctly with some input and return a correct result, this input should not be rejected.

2022-11-15 21:08 UTC, Ruishenl commented
what's the status of this pr ? is it ready to be merged yet ?

2022-11-15 21:11 UTC, AlirezaMorsali commented
> what's the status of this pr ? is it ready to be merged yet ?

Haven't gotten any chance to work on it, as there were more urgent issues. In particular, the traffic-light PR should be ready, just waiting for reviews.

2022-11-18 01:32 UTC, Ruishenl requested changes

2022-11-18 01:32 UTC, Ruishenl commented on invertedai/common.py
> +    def check_passwords_match(cls, values):
This function name needs to be changed

2022-11-18 17:55 UTC, Ruishenl approved these changes

2022-11-22 01:09 UTC, merged